apiVersion: apps/v1
kind: Deployment
metadata: 
  name: "{{.Values.name }}"
spec: 
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      app: "{{.Values.name }}"
  template: 
    metadata: 
      labels:
        app: "{{.Values.name }}"
    spec: 
      containers:
        - name: "{{.Values.name }}"
          image: {{ .Values.deployement.image }}:{{ .Values.deployement.tag }}
          imagePullPolicy:  {{ .Values.deployement.pullPolicy }}
          ports:
            - containerPort: 4242
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: DB_SERVER
              value: postgres
