apiVersion: v1
kind: Service
metadata: 
  name: {{  .Values.nameService | quote }}
  namespace: {{ .Values.namespaces.name }}
spec:
  selector:
    app: "{{ .Values.name }}"
  type: LoadBalancer
  ports:
    - port:  {{ .Values.app.port }}
      targetPort: {{ .Values.app.targetPort }}

      
      
      