apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ .Values.namespaces.name }}
  labels:
    app: postgres
    group: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        type: db
    spec:
      containers:
        - name: postgres
          image: postgres:{{ .Values.postgres.deployement.tag }}
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config

