apiVersion: v1
kind: ConfigMap
metadata: 
    name: postgres-config
    namespace: {{ .Values.namespaces.name }}
    labels:
        group: db
data: 
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
    POSTGRES_DB: etna-kub