apiVersion: v1
kind: ConfigMap
metadata: 
    name: postgres-config
    namespace: {{ .Values.namespaces.name }}
    labels:
        group: db
data: 
    POSTGRES_PASSWORD: {{ .Values.postgres.database.postgresPassword }}
    POSTGRES_USER: {{ .Values.postgres.database.postgresUser }}
    POSTGRES_DB: {{ .Values.postgres.database.postgresBb }}