apiVersion: v1
kind: Service
metadata: 
  name: app-service
spec:
  selector:
    app: kub-etna
  type: NodePort
  ports:
    - protocol: TCP 
      port: 4242
      targetPort: 4242
      nodePort: 30001
      