apiVersion: apps/v1
kind: Deployment
metadata: 
  name: kub-etna
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: kub-etna
  template: 
    metadata: 
      labels:
        app: kub-etna
    spec: 
      containers:
        - name: kub-etna
          image: my-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4242
